import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const WA='https://wa.me/94776380753',USD_LKR=305,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const vehicles=[
{id:'magnite',name:'Nissan Magnite',group:'suv',className:'Compact SUV',capacity:5,color:0xd8d8d8,image:'assets/fleet/magnite.jpg',fallback:'assets/fleet/magnite.svg'},
{id:'yaris-cross',name:'Toyota Yaris Cross',group:'suv',className:'Hybrid SUV',capacity:5,color:0xe6e6e6,image:'assets/fleet/yaris-cross.jpg',fallback:'assets/fleet/yaris-cross.svg'},
{id:'alto',name:'Suzuki Alto',group:'small',className:'Economy City',capacity:4,color:0xf1f1f1,image:'assets/fleet/alto.jpg',fallback:'assets/fleet/alto.svg'},
{id:'axio',name:'Toyota Axio',group:'sedan',className:'Executive Sedan',capacity:5,color:0xd9d9d9,image:'assets/fleet/axio.jpg',fallback:'assets/fleet/axio.svg'},
{id:'prius',name:'Toyota Prius',group:'sedan',className:'Hybrid Elite',capacity:5,color:0xe7e7e7,image:'assets/fleet/prius.jpg',fallback:'assets/fleet/prius.svg'},
{id:'vitz',name:'Toyota Vitz',group:'hatch',className:'Urban Compact',capacity:5,color:0xc8c8c8,image:'assets/fleet/vitz.jpg',fallback:'assets/fleet/vitz.svg'},
{id:'kdh',name:'Toyota KDH High Roof',group:'van',className:'Group Transit Van',capacity:11,color:0xe4e4e4,image:'assets/fleet/kdh.jpg',fallback:'assets/fleet/kdh.svg'},
{id:'xpander',name:'Mitsubishi Xpander',group:'suv',className:'7-Seater MPV',capacity:7,color:0xc5c5c5,image:'assets/fleet/xpander.jpg',fallback:'assets/fleet/xpander.svg'}];
const rates={small:{extra:40,hour:300,local:'20,000–50,000',abroad:'50,000–100,000',rows:[['Alto K / Alto C / Alto Auto',['3,000–5,000','4,000–6,000','5,500–7,500','7,500–9,500']],['Passo / Wagon R',['6,000–7,500','7,000–8,500','8,500–10,000','10,500–12,000']]]},hatch:{extra:50,hour:500,local:'30,000–40,000',abroad:'60,000–80,000',rows:[['Vitz / Nissan Leaf / Aqua / Vitz New / GP5 / Yaris',['6,500–7,500','8,500–9,000','10,500–11,500','13,000–14,500']]]},sedan:{extra:55,hour:500,local:'40,000',abroad:'80,000',rows:[['Insight / Shuttle / Prius / Premio / Axio Hybrid',['7,000–9,000','8,500–11,000','10,500–13,500','13,000–16,500']]]},suv:{extra:90,hour:1000,local:'30,000–150,000',abroad:'60,000–200,000',rows:[['Magnite / Vezel / Raize / CHR / Yaris Cross / VEZEL RS / Outlander / DFSK 580 / XPander',['7,000–11,500','9,000–14,000','11,000–17,000','13,500–20,000']]]},van:{extra:70,hour:550,local:'25,000–150,000',abroad:'50,000–200,000',rows:[['Daihatsu Hijet / Every Buddy / DFSK 7 Mini / KDH 10–11 Seater / KDH 222–14 Seater',['6,000–15,000','7,000–18,000','8,500–22,000','10,500–26,000']]]}};
const routes=[['CMB AIRPORT → KANDY',115],['CMB AIRPORT → COLOMBO',32],['COLOMBO → GALLE',126],['KANDY → ELLA',135],['KANDY → NUWARA ELIYA',77],['SIGIRIYA CULTURAL TRIANGLE',150]];
const state={vehicle:vehicles[6],service:'chauffeur',currency:'LKR',days:1,pack:100,distance:115,hours:0,gallery:0,exploded:false};
let bgRenderer,bgScene,bgMaterial,renderer,scene,camera,vehicleRoot,rock,resizeObserver,raf=0,last=0,pixelRatio=1,slow=0,audio;
const pointer={x:0,y:0,tx:0,ty:0};
const text=(s,v)=>{const e=$(s);if(e)e.textContent=v};
const mid=s=>{const n=s.replace(/,/g,'').split('–').map(Number);return n.length===2?(n[0]+n[1])/2:n[0]};
const fallback=v=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1000"><rect width="1600" height="1000" fill="#000"/><g fill="none" stroke="#fff"><ellipse cx="800" cy="540" rx="650" ry="250" stroke="#fef08a" opacity=".2"/><path d="M180 650h1240M270 580l210-150h640l210 150M500 430l90-125h420l90 125" stroke-width="9"/><circle cx="460" cy="650" r="105" stroke-width="10"/><circle cx="1140" cy="650" r="105" stroke-width="10"/><circle cx="460" cy="650" r="42" stroke="#fef08a" stroke-width="8"/><circle cx="1140" cy="650" r="42" stroke="#fef08a" stroke-width="8"/></g><text x="90" y="120" fill="#fef08a" font-family="monospace" font-size="32">[ SUNRISE / FLEET ARCHIVE ]</text><text x="90" y="195" fill="#fff" font-family="Arial" font-size="74" font-weight="900">${v.name.toUpperCase()}</text><text x="90" y="240" fill="#777" font-family="monospace" font-size="24">[ ${v.className.toUpperCase()} ] · [ ${v.capacity} SEATS ]</text></svg>`);
function estimate(){const r=rates[state.vehicle.group],raw=r.rows[0][1][[50,100,200,300].indexOf(state.pack)];if(!raw)return 300;const base=mid(raw)*state.days,extra=Math.max(0,state.distance-state.pack*state.days)*r.extra,hours=state.hours*r.hour,chauffeur=state.service==='chauffeur'?base*.08:0;return Math.round(base+extra+hours+300+chauffeur)}
function quote(){state.pack=+$('#packageKm').value;state.days=Math.max(1,+$('#days').value||1);state.distance=Math.max(0,+$('#distance').value||0);state.hours=Math.max(0,+$('#extraHours').value||0);const r=rates[state.vehicle.group],total=estimate();text('#quoteTotal',state.currency==='LKR'?`LKR ${total.toLocaleString('en-LK')}`:`USD ${Math.round(total/USD_LKR).toLocaleString()}`);text('#quoteMeta',`[ ${state.pack} KM/DAY ] [ ${r.extra} LKR/KM EXTRA ] [ ${r.hour} LKR/HOUR ] [ DOC 300 LKR ]`);text('#depositLocal','LKR '+r.local);text('#depositAbroad','LKR '+r.abroad);text('#selectedVehicle','[ '+state.vehicle.name.toUpperCase()+' ]')}
function selectVehicle(id){const v=vehicles.find(x=>x.id===id);if(!v)return;state.vehicle=v;const select=$('#vehicleSelect');if(select)select.value=id;$$('.fleet-card').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));text('#showroomVehicle',v.name.toUpperCase());text('#showroomClass',v.className.toUpperCase());text('#showroomSeats',v.capacity+' SEATS');text('#calculatorVehicle',v.name.toUpperCase());text('#calculatorClass',v.className.toUpperCase());quote();buildModel();chime(660)}
function buildRoutes(){const h=$('#routePresets');if(!h)return;routes.forEach(([name,km],i)=>{const b=document.createElement('button');b.className='route-chip'+(i?'':' active');b.innerHTML=`<span>0${i+1}</span><strong>${name}</strong><em>${km} KM*</em>`;b.onclick=()=>{$('#distance').value=km;$('#pickup').value=name;$$('.route-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');quote();chime(720)};h.appendChild(b)})}
function safeImage(img,v){if(!img)return;img.addEventListener('error',()=>{if(img.dataset.fallback==='1'){img.onerror=null;img.src=fallback(v);return}img.dataset.fallback='1';img.src=v.fallback},{once:true})}
function buildFleet(){const h=$('#fleetCards');if(!h)return;h.innerHTML='';vehicles.forEach((v,i)=>{const b=document.createElement('button');b.className='fleet-card';b.dataset.id=v.id;b.type='button';b.innerHTML=`<div class="fleet-image"><img src="${v.image}" alt="${v.name} — Sunrise Cabs" loading="lazy" decoding="async"><span class="image-index mono">0${i+1}</span></div><div class="fleet-card-body"><div class="mono">[ ${v.className} ]</div><h3>${v.name}</h3><div class="fleet-meta"><span>${v.capacity} PASSENGERS</span><span>SELECT →</span></div></div>`;safeImage($('img',b),v);b.onclick=()=>selectVehicle(v.id);h.appendChild(b)});selectVehicle(state.vehicle.id)}
function buildGallery(){const h=$('#galleryGrid');if(!h)return;h.innerHTML='';vehicles.forEach((v,i)=>{const f=document.createElement('figure');f.className='archive-card';f.tabIndex=0;f.innerHTML=`<div class="archive-media"><img src="${v.image}" alt="${v.name} — Sunrise Cabs" loading="lazy" decoding="async"><div class="archive-scan"></div><div class="archive-label mono">[ 0${i+1} / 08 ] · ${v.group}</div></div><figcaption><div><h3>${v.name}</h3><p class="mono">${v.className} · ${v.capacity} SEATS</p></div><span class="archive-arrow">↗</span></figcaption>`;safeImage($('img',f),v);f.onclick=()=>openLightbox(i);f.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openLightbox(i)};h.appendChild(f)});if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in-view')),{threshold:.25});$$('.archive-card').forEach(x=>io.observe(x))}}
function buildRates(){const h=$('#rateRows');if(!h)return;h.innerHTML='';Object.values(rates).forEach(r=>r.rows.forEach(row=>{const e=document.createElement('div');e.className='rate-row';e.innerHTML=`<div class="rate-name"><span class="mono">[ RATE CLASS ]</span><strong>${row[0]}</strong></div>${row[1].map(x=>`<span>${x}</span>`).join('')}<span>${r.extra} LKR/KM<br>${r.hour} LKR/HOUR</span>`;h.appendChild(e)}))}
function buildModel(){if(!vehicleRoot)return;vehicleRoot.clear();const v=state.vehicle,van=v.id==='kdh',mpv=v.id==='xpander',w=van?3.7:mpv?3.35:3.15,l=van?5.2:mpv?4.7:['alto','vitz'].includes(v.id)?4.15:4.55,h=van?1.45:1;const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,l,16,7,20),new THREE.MeshPhysicalMaterial({color:v.color,metalness:.92,roughness:.13,clearcoat:1,clearcoatRoughness:.04}));body.position.y=.95;vehicleRoot.add(body);const glass=new THREE.Mesh(new THREE.BoxGeometry(w*.84,.7,l*.55,12,5,14),new THREE.MeshPhysicalMaterial({color:0x11161b,metalness:.5,roughness:.08,clearcoat:1}));glass.position.y=1.65;vehicleRoot.add(glass);for(const x of[-w*.38,w*.38])for(const z of[-l*.34,l*.34]){const tyre=new THREE.Mesh(new THREE.CylinderGeometry(.43,.43,.34,28),new THREE.MeshStandardMaterial({color:0x050505,roughness:.3,metalness:.5}));tyre.rotation.z=Math.PI/2;tyre.position.set(x,.43,z);vehicleRoot.add(tyre);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.36,24),new THREE.MeshStandardMaterial({color:0xbdbdbd,metalness:1,roughness:.12}));rim.rotation.z=Math.PI/2;rim.position.set(x,.43,z);vehicleRoot.add(rim)}const lightMat=new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xfef08a,emissiveIntensity:3});for(const x of[-w*.27,w*.27]){const light=new THREE.Mesh(new THREE.BoxGeometry(w*.18,.13,.08),lightMat);light.position.set(x,1.08,l*.505);vehicleRoot.add(light)}if(state.exploded)vehicleRoot.children.forEach((o,i)=>{o.position.y+=(i+1)*.05;o.rotation.z+=(i%2?1:-1)*.03})}
const bgV=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}`;
const bgF=`precision highp float;varying vec2 vUv;uniform float uTime;uniform vec2 uPointer;void main(){vec2 uv=vUv-.5;uv.x*=1.6;float t=uTime*.055,f=0.;for(int i=0;i<6;i++){float n=float(i);vec2 c=.34*vec2(sin(t*(.45+n*.09)+n*1.8),cos(t*(.36+n*.07)+n));f+=smoothstep(.24,0.,length(uv-c));}float glow=.035/(.13+length(uv-uPointer*.18));float v=clamp(f*.035+glow*.01,0.,.11);gl_FragColor=vec4(vec3(v),1.);}`;
function initBackground(){const c=$('#bgCanvas');if(!c)return;bgScene=new THREE.Scene();const cam=new THREE.Camera();bgRenderer=new THREE.WebGLRenderer({canvas:c,antialias:false,powerPreference:'high-performance'});bgRenderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));bgRenderer.setClearColor(0x000000,1);bgMaterial=new THREE.ShaderMaterial({vertexShader:bgV,fragmentShader:bgF,uniforms:{uTime:{value:0},uPointer:{value:new THREE.Vector2()}}});bgScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),bgMaterial));const resize=()=>bgRenderer.setSize(innerWidth,visualViewport?.height||innerHeight,false);resize();addEventListener('resize',resize,{passive:true});const loop=t=>{bgMaterial.uniforms.uTime.value=t*.001;bgMaterial.uniforms.uPointer.value.lerp(new THREE.Vector2(pointer.x,pointer.y),.06);bgRenderer.render(bgScene,cam);requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function initShowroom(){const mount=$('#showroom');if(!mount)return;const box=mount.getBoundingClientRect();if(box.width<2||box.height<2){requestAnimationFrame(initShowroom);return}renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});pixelRatio=Math.min(devicePixelRatio||1,1.5);renderer.setPixelRatio(pixelRatio);renderer.setSize(box.width,box.height,false);renderer.setClearColor(0x000000,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,box.width/box.height,.1,100);camera.position.set(0,2.1,8.8);scene.add(new THREE.HemisphereLight(0x312e81,0x000000,1.4));const key=new THREE.SpotLight(0xffffff,7,30,Math.PI/5,.35,1);key.position.set(4,7,6);scene.add(key);const rim=new THREE.DirectionalLight(0xc084fc,4);rim.position.set(-4,3,-6);scene.add(rim);const gold=new THREE.PointLight(0xfef08a,18,18,2);gold.position.set(-4,2,-3);scene.add(gold);vehicleRoot=new THREE.Group();scene.add(vehicleRoot);buildModel();rock=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2,4),new THREE.MeshPhysicalMaterial({color:0x14271b,roughness:.88,metalness:.05,clearcoat:.2}));rock.position.set(-4.1,2.4,-3.6);scene.add(rock);resizeObserver=new ResizeObserver(es=>es.forEach(e=>{const w=e.contentRect.width,h=e.contentRect.height;if(w>2&&h>2){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}}));resizeObserver.observe(mount);mount.addEventListener('pointermove',e=>{const r=mount.getBoundingClientRect();pointer.tx=(e.clientX-r.left)/r.width*2-1;pointer.ty=-((e.clientY-r.top)/r.height*2-1)});const loop=t=>{const d=Math.min(.05,(t-last)/1000||.016);last=t;if(d>.0166)slow++;else slow=Math.max(0,slow-2);if(slow>=45&&pixelRatio>1){pixelRatio=Math.max(1,pixelRatio-.25);renderer.setPixelRatio(pixelRatio);slow=0;text('#tier','TIER-2 ADAPTIVE')}text('#fps',Math.round(1/Math.max(d,.001))+' FPS');pointer.x+=(pointer.tx-pointer.x)*.08;pointer.y+=(pointer.ty-pointer.y)*.08;vehicleRoot.rotation.y+=(pointer.x*.55-vehicleRoot.rotation.y)*.055;vehicleRoot.rotation.x+=(pointer.y*.18-vehicleRoot.rotation.x)*.055;vehicleRoot.position.y=Math.sin(t*.0012)*.08;rock.rotation.x+=d*.05;rock.rotation.y+=d*.08;rock.position.y=2.4+Math.sin(t*.0007)*.2;renderer.render(scene,camera);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop)}
function viewport(){const update=()=>document.documentElement.style.setProperty('--vh',(visualViewport?.height||innerHeight)+'px');update();visualViewport?.addEventListener('resize',update,{passive:true});new ResizeObserver(update).observe(document.documentElement)}
function navigation(){$$('[data-go]').forEach(b=>b.addEventListener('click',()=>{document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'});$('#mobileSheet')?.classList.remove('open')}));$('#menuButton')?.addEventListener('click',()=>$('#mobileSheet')?.classList.toggle('open'))}
function calculator(){const select=$('#vehicleSelect');if(!select)return;vehicles.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=v.name;select.appendChild(o)});['distance','days','packageKm','extraHours'].forEach(id=>$('#'+id)?.addEventListener('input',quote));select.addEventListener('change',e=>selectVehicle(e.target.value));$$('#serviceToggle button').forEach(b=>b.addEventListener('click',()=>{state.service=b.dataset.value;$$('#serviceToggle button').forEach(x=>x.classList.toggle('active',x===b));quote();chime(540)}));$$('#currencyToggle button').forEach(b=>b.addEventListener('click',()=>{state.currency=b.dataset.value;$$('#currencyToggle button').forEach(x=>x.classList.toggle('active',x===b));quote();chime(780)}));$('#chauffeurInfo')?.addEventListener('click',()=>$('#serviceInfo')?.classList.add('open'));$('#closeServiceInfo')?.addEventListener('click',()=>$('#serviceInfo')?.classList.remove('open'));$('#explode')?.addEventListener('click',()=>{state.exploded=!state.exploded;$('#explode').classList.toggle('active',state.exploded);buildModel();chime(900)})}
function dispatch(){const total=estimate(),message=`SUNRISE CABS — BOOKING INQUIRY\n\nName: ${$('#name').value||'Not provided'}\nTravel date / flight: ${$('#date').value||'Not provided'}\nVehicle: ${state.vehicle.name}\nClass: ${state.vehicle.className}\nPassengers: ${$('#passengers').value||2}\nService: ${state.service==='chauffeur'?'With chauffeur':'Self-drive'}\nRoute: ${$('#pickup').value||'Not provided'}\nDays: ${state.days}\nPackage: ${state.pack} km/day\nDistance: ${state.distance} km\nExtra hours: ${state.hours}\nEstimated total: ${state.currency==='LKR'?`LKR ${total.toLocaleString('en-LK')}`:`USD ${Math.round(total/USD_LKR)}`}\nNotes: ${$('#notes').value||'None'}\n\nPlease confirm availability and final quotation.`;window.open(WA+'?text='+encodeURIComponent(message),'_blank','noopener')}
function chime(f=620){try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(f*1.6,t+.18);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.035,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.25);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.26)}catch{}}
function openLightbox(i){state.gallery=(i+vehicles.length)%vehicles.length;const v=vehicles[state.gallery],box=$('#lightbox'),img=$('#lightboxImage');if(!box||!img)return;img.onerror=()=>{if(img.dataset.fallback==='1'){img.onerror=null;img.src=fallback(v);return}img.dataset.fallback='1';img.src=v.fallback};img.dataset.fallback='0';img.src=v.image;img.alt=`${v.name} — Sunrise Cabs`;$('#lightboxTitle').textContent=v.name;$('#lightboxMeta').textContent=`[ ${v.className.toUpperCase()} ] · [ ${v.capacity} SEATS ] · [ SRI LANKA ]`;box.classList.add('open');box.setAttribute('aria-hidden','false');chime(880)}
function lightbox(){$('#lbClose')?.addEventListener('click',()=>{$('#lightbox').classList.remove('open');$('#lightbox').setAttribute('aria-hidden','true')});$('#lbPrev')?.addEventListener('click',()=>openLightbox(state.gallery-1));$('#lbNext')?.addEventListener('click',()=>openLightbox(state.gallery+1));addEventListener('keydown',e=>{if(e.key==='Escape')$('#lbClose')?.click();if(e.key==='ArrowLeft'&&$('#lightbox').classList.contains('open'))openLightbox(state.gallery-1);if(e.key==='ArrowRight'&&$('#lightbox').classList.contains('open'))openLightbox(state.gallery+1)})}
function cursor(){const c=$('#cursor');if(!c||matchMedia('(pointer:coarse)').matches){c?.remove();return}let x=0,y=0,tx=0,ty=0;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY});$$('a,button,.archive-card,.fleet-card').forEach(e=>{e.addEventListener('mouseenter',()=>c.classList.add('large'));e.addEventListener('mouseleave',()=>c.classList.remove('large'))});const loop=()=>{x+=(tx-x)*.18;y+=(ty-y)*.18;c.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`;requestAnimationFrame(loop)};loop()}
function scrollFx(){if(window.Lenis&&window.gsap){const lenis=new Lenis({duration:1.05,smoothWheel:true,smoothTouch:false});const tick=t=>{lenis.raf(t);requestAnimationFrame(tick)};requestAnimationFrame(tick);gsap.registerPlugin(ScrollTrigger);gsap.utils.toArray('.reveal').forEach(e=>gsap.fromTo(e,{y:55,opacity:0},{y:0,opacity:1,duration:1,ease:'power4.out',scrollTrigger:{trigger:e,start:'top 88%',once:true}}));gsap.to('#heroTitle',{yPercent:-12,scrollTrigger:{trigger:'#hero',start:'top top',end:'bottom top',scrub:true}});ScrollTrigger.refresh()}}
function cleanup(){cancelAnimationFrame(raf);resizeObserver?.disconnect();scene?.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){const m=Array.isArray(o.material)?o.material:[o.material];m.forEach(x=>x.dispose())}});renderer?.dispose();renderer?.forceContextLoss?.();bgRenderer?.dispose();bgRenderer?.forceContextLoss?.()}
addEventListener('beforeunload',cleanup);
document.addEventListener('DOMContentLoaded',()=>{viewport();navigation();buildRoutes();buildFleet();buildGallery();buildRates();calculator();quote();lightbox();cursor();$('#dispatch')?.addEventListener('click',dispatch);addEventListener('pointerdown',()=>{try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}},{once:true,passive:true});initBackground();initShowroom();scrollFx()});