const SunriseFinalFixes=(()=>{
  const vehicles=[
    ['magnite','Nissan Magnite','Compact SUV',5],['yaris-cross','Toyota Yaris Cross','Hybrid SUV',5],['alto','Suzuki Alto','Economy City',4],['axio','Toyota Axio','Executive Sedan',5],['prius','Toyota Prius','Hybrid Elite',5],['vitz','Toyota Vitz','Urban Compact',5],['kdh','Toyota KDH High Roof','Group Transit Van',11],['xpander','Mitsubishi Xpander','7-Seater MPV',7]
  ];
  const cleanSvg=(name,category,seats)=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 700"><rect width="1200" height="700" fill="#050505"/><g fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"><path d="M130 470h940M235 470l125-130h480l130 130M360 340l55-90h370l55 90"/><circle cx="330" cy="470" r="78"/><circle cx="870" cy="470" r="78"/><circle cx="330" cy="470" r="29" stroke="#fef08a"/><circle cx="870" cy="470" r="29" stroke="#fef08a"/><path d="M475 375h250" stroke="#999" stroke-width="5"/></g><ellipse cx="600" cy="480" rx="500" ry="155" fill="none" stroke="#fef08a" stroke-opacity=".14" stroke-width="3"/><text x="60" y="90" fill="#fef08a" font-family="monospace" font-size="22">[ SUNRISE / FLEET ]</text><text x="60" y="130" fill="#777" font-family="monospace" font-size="16">[ ${category.toUpperCase()} ] · [ ${seats} SEATS ]</text><text x="60" y="640" fill="#fff" font-family="Arial,sans-serif" font-size="28" font-weight="700">${name.toUpperCase()}</text></svg>`)}`;
  const list=()=>vehicles.map((v,i)=>({id:v[0],name:v[1],category:v[2],seats:v[3],index:i}));
  function fallback(img,v){const holder=img.closest('.fleet-image,.archive-media');if(!holder)return;img.onerror=null;img.alt='';img.removeAttribute('src');img.style.visibility='hidden';img.style.opacity='0';holder.style.backgroundImage=`url("${cleanSvg(v.name,v.category,v.seats)}")`;holder.style.backgroundPosition='center';holder.style.backgroundSize='cover';holder.style.backgroundRepeat='no-repeat';holder.classList.add('fallback-active')}
  function hydrate(img,v){if(!img||img.dataset.sunriseReady==='1')return;img.dataset.sunriseReady='1';const holder=img.closest('.fleet-image,.archive-media');if(holder){holder.style.backgroundImage='none';holder.classList.remove('fallback-active')}img.style.visibility='hidden';img.style.opacity='0';const probe=new Image();probe.onload=()=>{img.src=probe.currentSrc||probe.src;img.alt=`${v.name} — Sunrise Cabs`;img.style.visibility='visible';img.style.opacity='1'};probe.onerror=()=>fallback(img,v);probe.src=`assets/fleet/${v.id}.jpg`}
  function patch(){const vs=list();document.querySelectorAll('.fleet-card').forEach((card,i)=>{const id=card.dataset.id||vs[i]?.id;const v=vs.find(x=>x.id===id)||vs[i];const img=card.querySelector('img');if(v&&img)hydrate(img,v)});document.querySelectorAll('.archive-card').forEach((card,i)=>{const v=vs[i];const img=card.querySelector('img');if(v&&img)hydrate(img,v)})}
  function styles(){if(document.getElementById('sunriseFinalStyle'))return;const s=document.createElement('style');s.id='sunriseFinalStyle';s.textContent=`.header{background:#000;backdrop-filter:none;-webkit-backdrop-filter:none}main>section{scroll-margin-top:96px}.fleet-image,.archive-media{background-color:#050505}.fleet-image img,.archive-media img{transition:opacity .35s ease,filter .6s var(--ease),transform .8s var(--ease)}@media(max-width:760px){.header{z-index:1000;padding-top:calc(12px + env(safe-area-inset-top));background:#000}.section{scroll-margin-top:84px}.section-heading h2{font-size:clamp(3.2rem,12.2vw,5.2rem);line-height:.76}.archive .section-heading{padding-top:18px}.archive-grid{gap:12px}.archive-media{aspect-ratio:16/10!important}.floating-status{display:none}.fleet-grid{gap:8px}.fleet-image{aspect-ratio:1.22!important}.fleet-card-body{min-height:105px;display:flex;flex-direction:column;justify-content:space-between}.fleet-card-body h3{font-size:14px;line-height:1;margin:8px 0 12px}.fleet-meta{font-size:6.5px}}`;document.head.appendChild(s)}
  function boot(){styles();patch();const observer=new MutationObserver(patch);observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),10000);window.addEventListener('load',patch,{once:true})}
  return {boot}
})();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',SunriseFinalFixes.boot,{once:true});else SunriseFinalFixes.boot();
